### ISSUE TITLE
Shopware 5.6 compatibility

### ISSUE THREAD

**Issue by acris-cp** [wirecard/shopware-ee#118]
Hi Wirecard-Team!
We are waiting for the Wirecard Plugin which is possible to install for Shopware >= 5.6. Currently it is only available until Shopware 5.5.10.
When do you plan the release for the current Shopware version? Shopware 5.6 has been released before more then 3 weeks.
Thank you for your answer.

**Comment by cpfoser** [comment]
Hi @acris-cp 
we checked our latest shopware release and it is compatible with 5.6.0.
Currently we are investigating the compatibility to 5.6.1. As soon as the compatibility is given we update the information in the repository. 

Kind regards,
Wirecard Shop Systems Team
