### ISSUE TITLE
Error at Plugin installation "You're trying to decode an invalid JSON String"

### ISSUE THREAD

**Issue by chrizdee** [wirecard/shopware-ee#124]
When I try to install the plugin on Shopware 5.6.2, I get this error:

```
"You're trying to decode an invalid JSON String: <br />
<b>Fatal error</b>:  Uncaught ArgumentCountError: Too few arguments to function Shopware_Components_Translation::__construct(), 0 passed in /var/www/site/custom/plugins/WirecardElasticEngine/WirecardElasticEngine.php on line 295 and exactly 2 expected in /var/www/site//engine/Shopware/Components/Translation.php:50
Stack trace:
#0 /var/www/site/custom/plugins/WirecardElasticEngine/WirecardElasticEngine.php(295): Shopware_Components_Translation-&gt;__construct()
#1 /var/www/site/custom/plugins/WirecardElasticEngine/WirecardElasticEngine.php(269): WirecardElasticEngine\WirecardElasticEngine-&gt;updatePaymentTranslation('4', 167, 'Wirecard Kredit...', '0')
#2 /var/www/site/custom/plugins/WirecardElasticEngine/WirecardElasticEngine.php(145): WirecardElasticEngine\WirecardElasticEngine-&gt;translatePayments(Array)
#3 /var/www/site/custom/plugins/WirecardElasticEngine/Wirecar in <b>/var/www/site/engine/Shopware/Components/Translation.php</b> on line <b>50</b><br />
```

**Comment by serucee** [comment]
Hi @chrizdee ,

thank you for your feedback. We are not yet compatible with Shopware 5.6.2 but will work on it and keep you updated on the progress!

Best regards,
Wirecard Shop Systems Team

**Comment by johanndrews** [comment]
@serucee is it predictable when a new release will be released that is compatible with 5.6.2?

**Comment by vitali-graz** [comment]
Hi @chrizdee and @chrizdee ,

Quick update. Shopware 5.6.2 compatibility is planned into one of our upcoming Shopware releases. No fixed date at this point. Stay tuned to our future updates.

Best regards,
Wirecard Shop Systems Team

**Comment by johanndrews** [comment]
@vitali-graz honestly, where's the message's content? Sure you will plan it for the upcoming Shopware releases, you need to... The question is when...

**Comment by klausmad** [comment]
It becomes increasingly obvious that Wirecard no longer has any interest in attracting the up-and-coming Shopware community - which expands every month to hundreds of potential wirecard customers - or to retain existing customers. One can understand that a company focuses on diverse topics, but after years of collecting customers letting them down "technically" is simply an unworthy approach. I revoke all positive statements about Wirecard plugin, because there is currently nothing positive about it anymore and all statements of contact persons are "spongy" and implausible empty promises.

**Comment by cpfoser** [comment]
Hello, 

we are currently in the last steps to release a new Shopware version.
Afterwards, we will make our extension compatible with the latest Shopware version. 

Best regards, 
Wirecard Shop Systems Team

**Comment by pretzelhands** [comment]
Hello,

this issue has been resolved with our [latest release](https://github.com/wirecard/shopware-ee/releases/tag/1.3.9). Thank you for your patience!

Best regards,
Wirecard Shop Systems Team
