### ISSUE TITLE
SW plugin ready for PHP 7.3.x ?

### ISSUE THREAD

**Issue by klausmad** [wirecard/shopware-ee#127]
https://github.com/wirecard/shopware-ee/issues/122

Reopen this, because this ticket is not closed... still we have no PHP 7.3 compatibility

**Comment by vitali-graz** [comment]
Hello @klausmad 

You are correct. I've reopened the referenced issue. Any progress on the topic of PHP 7.3 will be communicated there.

Best regards,
Wirecard Shop Systems Team
