### ISSUE TITLE
Wirecard Plugin hangs on install (sometimes)

### ISSUE THREAD

**Issue by romanWienicke** [wirecard/shopware-ee#129]
In some conditions the Installer stalls with a "ring of death". 

This is caused by the following line when the payment translation is executed:
(WirecardElasticEngine.php / Line 297)
`  $translationObject = new \Shopware_Components_Translation();`

the solution is to get the translation object from the container (for my code it worked after the change)
` $translationObject = $this->container->has('translation') ? $this->container->get('translation') : new \Shopware_Components_Translation();`

**Comment by rinnhofer** [comment]
Hello @romanWienicke ,

thank you for your contribution and solution proposal. We will look into this issue as soon as possible and update you on the progress.

Kind regards,
Wirecard Shop Systems Team

**Comment by pretzelhands** [comment]
Hello,

this issue has been resolved with our [latest release](https://github.com/wirecard/shopware-ee/releases/tag/1.3.9). Thank you for your patience!

Best regards,
Wirecard Shop Systems Team
