### ISSUE TITLE
SW Version tested and newest SW Version 5.6.4

### ISSUE THREAD

**Issue by klausmad** [wirecard/shopware-ee#170]
Hi,

sorry, I cannot agree with your overview, because for SW 5.6.x the minimum PHP version has been increased to PHP 7.2 or higher.

![grafik](https://user-images.githubusercontent.com/22545981/74525948-9fff1c00-4f22-11ea-9c28-2e8e806362f0.png)

Is it please possible to force testing with PHP 7.3.x soon ? Because SW 5.6.x recommends PHP 7.3. and beginning with SW 5.6.5 PHP 7.4.X is supported...

You should finally say goodbye to the old PHP  5.6, 7,0, 7,1 versions because nobody uses them anymore ...  https://docs.shopware.com/en/shopware-5-en/update-guides/update-guide-shopware-56

Please can you answer me, why you test your plugin in february 2020 with SW 5.6.2 (released 09/2019 !!) when the newest version is 5.6.4 (released 18.12.2019) ... your plugin update 1.3.10 is useless for most of SW User, because most of them are on current version and not 4 month behind ... **can you please test a current version** !!!!

**Comment by vitali-graz** [comment]
Hello @klausmad,

Thank you for your valuable feedback!
You are correct, the current version was tested with PHP 7.2. We will update the release note and fix the release script accordingly.

Both the PHP versions and newer shop system versions for Shopware are on our roadmap but please keep in mind that we are maintaining the compatibility, feature development and issue resolution of 10 vastly different shop extensions, so the use our development resources is prioritized against individual topics across all extensions.
We hear you. the support for newer PHP versions and shop system versions is important and we will provide the updates in time.

Thank you for understanding,
Best regards,
Wirecard Shop Systems Team
