### ISSUE TITLE
Shopware update 5.6.4

### ISSUE THREAD

**Issue by l4ci** [wirecard/shopware-ee#203]
Hello, we updated to Shopware 5.6.4 before the shopware plugin was released back in the store (so we didn't get any incompatibility notices). So far everything seems to work, but we would love to have the official compatibility support.

**Comment by vitali-graz** [comment]
Hi @l4ci ,

thanks for the info. We plan to test the additional Shopware and PHP versions and extend our compatibility range in the near future. At this moment we cannot commit to any concrete dates but stay tuned to our release updates.

Best regards,
Wirecard Shop Systems Team
